=== ddaugher/Dasient_Integration/DasientIntegration-ejb/test/fixtures/dataset.dtd
<!ELEMENT dataset (
    CONTROL_PANEL*,
    REVISION*,
    WEB_SERVER*,
    CLEAN_HISTORY*,
    CLEAN_FILE*,
    CLEAN_FILE_BACKUP*,
    SCAN_HISTORY*,
    CLEAN_HISTORY_TRIGGERS*,
    REVISION_TYPE*,
    RULE*,
    RULE_ACTION*,
    RULE_STATE*,
    RULE_REVISION*,
    CLEAN_RULE_MATCH*,
    DOMAIN*,
    FAILURE*,
    MALICIOUS_URL*,
    MALICIOUS_SOURCE_CODE_SNIPPET*,
    ON_BLACKLIST*,
    PENDING_CLEAN*,
    PENDING_CLEAN_TRIGGERS*,
    REQUEST_IGNORED*,
    RULE_REVISION_CHAIN*,
    RULE_TERM*,
    SCANNED_URL*,
    SUSPICIOUS_URL*,
    SUSPICIOUS_SOURCE_CODE_SNIPPET*,
    WEB_SERVER_ACTIVITY*,
    WEB_STORAGE*,
    WEB_SERVER_STORAGE*)>

<!ELEMENT CONTROL_PANEL EMPTY>
<!ATTLIST CONTROL_PANEL
    CONTROL_PANEL_ID CDATA #REQUIRED
    DB_HOST CDATA #REQUIRED
    LAST_SYNCED_DOMAIN_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SYNC_ENABLED CDATA #REQUIRED
>

<!ELEMENT REVISION EMPTY>
<!ATTLIST REVISION
    REVISION_ID CDATA #REQUIRED
    REVISION_AUTHOR CDATA #REQUIRED
    REVISION_COMMENT CDATA #REQUIRED
    REVISION_TIME CDATA #REQUIRED
>

<!ELEMENT WEB_SERVER EMPTY>
<!ATTLIST WEB_SERVER
    CLEAN_SCHEDULE CDATA #REQUIRED
    CONTROL_PANEL_ID CDATA #REQUIRED
    IP_ADDRESS CDATA #REQUIRED
    IS_DELETED CDATA #REQUIRED
    LOGICAL_SERVER_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    WEB_SERVER_ID CDATA #REQUIRED
>

<!ELEMENT CLEAN_HISTORY EMPTY>
<!ATTLIST CLEAN_HISTORY
    ACCOUNT_ID CDATA #REQUIRED
    CLEAN_HISTORY_ID CDATA #REQUIRED
    CONTROL_PANEL_ID CDATA #REQUIRED
    FINISH_TIME CDATA #REQUIRED
    REVISION_ID CDATA #REQUIRED
    SCHEDULE_TIME CDATA #REQUIRED
    START_TIME CDATA #REQUIRED
    WEB_SERVER_ID CDATA #REQUIRED
    WEB_USERNAME CDATA #REQUIRED
>

<!ELEMENT CLEAN_FILE EMPTY>
<!ATTLIST CLEAN_FILE
    CLEAN_FILE_ID CDATA #REQUIRED
    CLEAN_HISTORY_ID CDATA #REQUIRED
    CTIME CDATA #REQUIRED
    MODE CDATA #REQUIRED
    MTIME CDATA #REQUIRED
    NEW_CTIME CDATA #REQUIRED
    hash CDATA #REQUIRED
    path CDATA #REQUIRED
>

<!ELEMENT CLEAN_FILE_BACKUP EMPTY>
<!ATTLIST CLEAN_FILE_BACKUP
    CLEAN_FILE_ID CDATA #REQUIRED
    CONTENT CDATA #REQUIRED
>

<!ELEMENT SCAN_HISTORY EMPTY>
<!ATTLIST SCAN_HISTORY
    COMPLETED_AT CDATA #IMPLIED
    CREATE_TMS CDATA #REQUIRED
    HOSTNAME CDATA #IMPLIED
    RAW_REQUEST CDATA #IMPLIED
    RAW_RESPONSE CDATA #IMPLIED
    REQUEST_ID CDATA #IMPLIED
    SCAN_HISTORY_ID CDATA #REQUIRED
    STATUS CDATA #IMPLIED
    STATUS_URL CDATA #IMPLIED
>

<!ELEMENT CLEAN_HISTORY_TRIGGERS EMPTY>
<!ATTLIST CLEAN_HISTORY_TRIGGERS
    CLEAN_HISTORY_ID CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
>

<!ELEMENT REVISION_TYPE EMPTY>
<!ATTLIST REVISION_TYPE
    DISPLAY_NAME CDATA #REQUIRED
    REVISION_TYPE_ID CDATA #REQUIRED
>

<!ELEMENT RULE EMPTY>
<!ATTLIST RULE
    RULE_ID CDATA #REQUIRED
>

<!ELEMENT RULE_ACTION EMPTY>
<!ATTLIST RULE_ACTION
    DISPLAY_NAME CDATA #REQUIRED
    RULE_ACTION_ID CDATA #REQUIRED
>

<!ELEMENT RULE_STATE EMPTY>
<!ATTLIST RULE_STATE
    ACTION_ID CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    RULE_STATE_ID CDATA #REQUIRED
>

<!ELEMENT RULE_REVISION EMPTY>
<!ATTLIST RULE_REVISION
    IS_DELETED CDATA #REQUIRED
    REVISION_ID CDATA #REQUIRED
    RULE_ID CDATA #REQUIRED
    RULE_REVISION_ID CDATA #REQUIRED
    STATE_ID CDATA #REQUIRED
    TYPE_ID CDATA #REQUIRED
>

<!ELEMENT CLEAN_RULE_MATCH EMPTY>
<!ATTLIST CLEAN_RULE_MATCH
    CLEAN_FILE_ID CDATA #REQUIRED
    CLEAN_RULE_MATCH_ID CDATA #REQUIRED
    END_POS CDATA #REQUIRED
    LITERAL CDATA #REQUIRED
    RULE_REVISION_ID CDATA #REQUIRED
    START_POS CDATA #REQUIRED
>

<!ELEMENT DOMAIN EMPTY>
<!ATTLIST DOMAIN
    DOMAIN_ID CDATA #REQUIRED
    IS_DELETED CDATA #REQUIRED
    HSPHERE_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    NEXT_SCAN CDATA #REQUIRED
    STATUS CDATA #IMPLIED
    UPDATE_TMS CDATA #REQUIRED
    CONTROL_PANEL_ID CDATA #REQUIRED
>

<!ELEMENT FAILURE EMPTY>
<!ATTLIST FAILURE
    FAILURE_ID CDATA #REQUIRED
    CODE CDATA #REQUIRED
    REASON CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
>

<!ELEMENT MALICIOUS_URL EMPTY>
<!ATTLIST MALICIOUS_URL
    MALICIOUS_URL_ID CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
    URL CDATA #REQUIRED
>

<!ELEMENT MALICIOUS_SOURCE_CODE_SNIPPET EMPTY>
<!ATTLIST MALICIOUS_SOURCE_CODE_SNIPPET
    MALICIOUS_URL_ID CDATA #REQUIRED
    SNIPPET CDATA #REQUIRED
    SNIPPET_ID CDATA #REQUIRED
>

<!ELEMENT ON_BLACKLIST EMPTY>
<!ATTLIST ON_BLACKLIST
    NAME CDATA #REQUIRED
    ON_BLACKLIST_ID CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
>

<!ELEMENT PENDING_CLEAN EMPTY>
<!ATTLIST PENDING_CLEAN
    ACCOUNT_ID CDATA #REQUIRED
    CONTROL_PANEL_ID CDATA #REQUIRED
    PENDING_CLEAN_ID CDATA #REQUIRED
    QUERY_TIME CDATA #IMPLIED
    SCHEDULE_TIME CDATA #REQUIRED
    WEB_SERVER_ID CDATA #REQUIRED
    WEB_USERNAME CDATA #REQUIRED
>

<!ELEMENT PENDING_CLEAN_TRIGGERS EMPTY>
<!ATTLIST PENDING_CLEAN_TRIGGERS
    PENDING_CLEAN_ID CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
>

<!ELEMENT REQUEST_IGNORED EMPTY>
<!ATTLIST REQUEST_IGNORED
    ACTUAL_IP CDATA #REQUIRED
    REQUESTED_IP CDATA #REQUIRED
    REQUEST_IGNORED_ID CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
>

<!ELEMENT RULE_REVISION_CHAIN EMPTY>
<!ATTLIST RULE_REVISION_CHAIN
    NEXT_RULE_REVISION_ID CDATA #REQUIRED
    PREV_RULE_REVISION_ID CDATA #REQUIRED
>

<!ELEMENT RULE_TERM EMPTY>
<!ATTLIST RULE_TERM
    RULE_STATE_ID CDATA #REQUIRED
    RULE_TERM_ID CDATA #REQUIRED
    TERM CDATA #REQUIRED
>

<!ELEMENT SCANNED_URL EMPTY>
<!ATTLIST SCANNED_URL
    SCANNED_URL_ID CDATA #REQUIRED
    SCAN_HISTORY_ID CDATA #REQUIRED
    URL CDATA #REQUIRED
>

<!ELEMENT SUSPICIOUS_URL EMPTY>
<!ATTLIST SUSPICIOUS_URL
    SCAN_HISTORY_ID CDATA #REQUIRED
    SUSPICIOUS_URL_ID CDATA #REQUIRED
    URL CDATA #REQUIRED
>

<!ELEMENT SUSPICIOUS_SOURCE_CODE_SNIPPET EMPTY>
<!ATTLIST SUSPICIOUS_SOURCE_CODE_SNIPPET
    SNIPPET CDATA #REQUIRED
    SNIPPET_ID CDATA #REQUIRED
    SUSPICIOUS_URL_ID CDATA #REQUIRED
>

<!ELEMENT WEB_SERVER_ACTIVITY EMPTY>
<!ATTLIST WEB_SERVER_ACTIVITY
    ACCESS_TIME CDATA #REQUIRED
    WEB_SERVER_ACTIVITY_ID CDATA #REQUIRED
    WEB_SERVER_ID CDATA #REQUIRED
>

<!ELEMENT WEB_STORAGE EMPTY>
<!ATTLIST WEB_STORAGE
    MAX_CONCURRENT_CLEANS CDATA #REQUIRED
    NAME CDATA #REQUIRED
    WEB_STORAGE_ID CDATA #REQUIRED
>

<!ELEMENT WEB_SERVER_STORAGE EMPTY>
<!ATTLIST WEB_SERVER_STORAGE
    WEB_SERVER_ID CDATA #REQUIRED
    WEB_STORAGE_ID CDATA #REQUIRED
>

=== ddaugher/Dasient_Integration/DasientIntegration-ejb/test/fixtures/CleanBrokerBeanTest.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>

    <CONTROL_PANEL
        CONTROL_PANEL_ID="1"
        NAME="cp.opentransfer.com"
        DB_HOST="pgsqlcp.opentransfer.com"
        SYNC_ENABLED="false"
        LAST_SYNCED_DOMAIN_ID="0" />

    <REVISION
        REVISION_ID="1"
        REVISION_AUTHOR="nobody@ecommerce.com"
        REVISION_COMMENT=""
        REVISION_TIME="2010-01-01 00:00:00"/>

    <WEB_SERVER
        WEB_SERVER_ID="1"
        CONTROL_PANEL_ID="1"
        NAME="web.opentransfer.com"
        IP_ADDRESS="127.0.0.1"
        LOGICAL_SERVER_ID="1"
        CLEAN_SCHEDULE="0"
        IS_DELETED="false" />

    <WEB_SERVER
        WEB_SERVER_ID="2"
        CONTROL_PANEL_ID="1"
        NAME="mismatch.opentransfer.com"
        IP_ADDRESS="127.0.0.2"
        LOGICAL_SERVER_ID="2"
        CLEAN_SCHEDULE="0"
        IS_DELETED="false" />

    <SCAN_HISTORY
        SCAN_HISTORY_ID="1"
        CREATE_TMS="2010-01-01 00:00:00"
        COMPLETED_AT="2010-01-01 00:00:00"
        RAW_RESPONSE="unspecified"
        HOSTNAME="test.com"
        STATUS_URL="http://localhost/no-status"
        STATUS="COMPLETED" />

    <SCAN_HISTORY
        SCAN_HISTORY_ID="2"
        CREATE_TMS="2010-01-01 00:00:00"
        COMPLETED_AT="2010-01-01 00:00:00"
        RAW_RESPONSE="unspecified"
        HOSTNAME="test.org"
        STATUS_URL="http://localhost/no-status"
        STATUS="COMPLETED" />

    <DOMAIN
        DOMAIN_ID="1"
        CONTROL_PANEL_ID="1"
        HSPHERE_ID="1"
        NAME="test.com"
        IS_DELETED="false"
        NEXT_SCAN="2010-01-01 00:00:00"
        UPDATE_TMS="2010-01-01 00:00:00"/>

    <PENDING_CLEAN
        PENDING_CLEAN_ID="1"
        CONTROL_PANEL_ID="1"
        WEB_SERVER_ID="1"
        ACCOUNT_ID="1"
        WEB_USERNAME="testuser"
        SCHEDULE_TIME="2010-01-01 00:00:00" />

</dataset>

=== ddaugher/Dasient_Integration/DasientIntegration-ejb/test/fixtures/common.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>

    <REVISION_TYPE REVISION_TYPE_ID="CREATE" DISPLAY_NAME="Create"/>
    <REVISION_TYPE REVISION_TYPE_ID="UPDATE" DISPLAY_NAME="Update"/>
    <REVISION_TYPE REVISION_TYPE_ID="DELETE" DISPLAY_NAME="Delete"/>
    <REVISION_TYPE REVISION_TYPE_ID="RESURRECT" DISPLAY_NAME="Resurrect"/>

    <RULE_ACTION RULE_ACTION_ID="ignore" DISPLAY_NAME="Ignore"/>
    <RULE_ACTION RULE_ACTION_ID="warn" DISPLAY_NAME="Warn"/>
    <RULE_ACTION RULE_ACTION_ID="clean" DISPLAY_NAME="Clean"/>
    <RULE_ACTION RULE_ACTION_ID="quarantine" DISPLAY_NAME="Quarantine"/>

</dataset>
